<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>..\Macad.Resources\Icons\App\App-MainLogo.ico</ApplicationIcon>  
    <StartupObject>Macad.Window.Program</StartupObject>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <RuntimeIdentifier Condition=" '$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition=" '$(Platform)' == 'x86'">win-x86</RuntimeIdentifier>
  </PropertyGroup>
  <Import Project="$(MMBuildPropsDir)\Macad.Publish.props" />
  <ItemGroup>
    <PackageReference Include="ControlzEx" />
    <PackageReference Include="Dirkster.AvalonDock" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" />
    <PackageReference Include="Fluent.Ribbon" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Tools\SourceGenerator\SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\Macad.Common\Macad.Common.csproj" />
    <ProjectReference Include="..\Macad.Core\Macad.Core.csproj" />
    <ProjectReference Include="..\Macad.Exchange\Macad.Exchange.csproj" />
    <ProjectReference Include="..\Macad.Interaction\Macad.Interaction.csproj" />
    <ProjectReference Include="..\Macad.Managed\Macad.Managed.vcxproj" />
    <ProjectReference Include="..\Macad.Occt\Macad.Occt.vcxproj" />
    <ProjectReference Include="..\Macad.Presentation\Macad.Presentation.csproj" />
    <ProjectReference Include="..\Macad.Resources\Macad.Resources.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Test.Core" />
    <InternalsVisibleTo Include="Test.Memory" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Macad.args.json" />
    <None Remove="Macad.csproj.DotSettings" />
    <None Remove="Properties\launchSettings.json" />
  </ItemGroup>
</Project>